-- Create tables for hot topics and recommended users
-- Migration timestamp: 20250125000004

-- Create hot_topics table (热门话题标签)
CREATE TABLE IF NOT EXISTS hot_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag VARCHAR(100) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  count INTEGER DEFAULT 0,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create recommended_users table (推荐关注用户)
CREATE TABLE IF NOT EXISTS recommended_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name VARCHAR(100) NOT NULL,
  avatar_url TEXT,
  role VARCHAR(50) NOT NULL,
  description TEXT,
  followers_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_hot_topics_is_active ON hot_topics(is_active);
CREATE INDEX IF NOT EXISTS idx_hot_topics_count ON hot_topics(count DESC);
CREATE INDEX IF NOT EXISTS idx_hot_topics_order ON hot_topics(order_index);
CREATE INDEX IF NOT EXISTS idx_recommended_users_is_active ON recommended_users(is_active);
CREATE INDEX IF NOT EXISTS idx_recommended_users_order ON recommended_users(order_index);

-- Enable Row Level Security
ALTER TABLE hot_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE recommended_users ENABLE ROW LEVEL SECURITY;

-- RLS Policies for hot_topics
-- Public can view active hot topics
CREATE POLICY "Public can view active hot topics"
ON hot_topics FOR SELECT
USING (is_active = true);

-- Service role can manage hot topics
CREATE POLICY "Service role can manage hot topics"
ON hot_topics FOR ALL
USING (auth.role() = 'service_role');

-- RLS Policies for recommended_users
-- Public can view active recommended users
CREATE POLICY "Public can view active recommended users"
ON recommended_users FOR SELECT
USING (is_active = true);

-- Service role can manage recommended users
CREATE POLICY "Service role can manage recommended users"
ON recommended_users FOR ALL
USING (auth.role() = 'service_role');

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers to automatically update updated_at
CREATE TRIGGER update_hot_topics_updated_at
BEFORE UPDATE ON hot_topics
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_recommended_users_updated_at
BEFORE UPDATE ON recommended_users
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- Insert initial sample data for hot topics
INSERT INTO hot_topics (tag, display_name, count, description, is_active, order_index) VALUES
  ('AI绘画教程', '#AI绘画教程', 1250, 'AI绘画相关教程和技巧分享', true, 1),
  ('大模型最新进展', '#大模型最新进展', 980, '大模型领域的最新动态和进展', true, 2),
  ('开源工具推荐', '#开源工具推荐', 856, '实用的开源工具和库推荐', true, 3),
  ('虚拟人技术', '#虚拟人技术', 723, '虚拟人技术和应用案例', true, 4),
  ('生成式AI应用', '#生成式AI应用', 689, '生成式AI在各领域的应用', true, 5)
ON CONFLICT (tag) DO NOTHING;

-- Note: For recommended users, you need to insert actual user IDs
-- Sample data structure (replace UUIDs with real user IDs from your auth.users table):
-- INSERT INTO recommended_users (user_id, display_name, avatar_url, role, description, followers_count, is_active, order_index) VALUES
--   ('your-user-id-1', 'AI 实验室', 'avatar-url-1', '技术先锋', '专注AI技术研究与分享', 5230, true, 1),
--   ('your-user-id-2', '科技观察员', 'avatar-url-2', '行业专家', '科技行业深度观察', 3450, true, 2),
--   ('your-user-id-3', '数字艺术家', 'avatar-url-3', '技术先锋', 'AI艺术创作实践者', 2890, true, 3);
