-- Create tables for market products (成果市集)
-- Migration timestamp: 20250125000005

-- Create market_products table (市集商品表)
CREATE TABLE IF NOT EXISTS market_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50) NOT NULL,
  icon_type VARCHAR(50) NOT NULL DEFAULT 'shield',
  icon_color VARCHAR(50) NOT NULL DEFAULT 'blue',
  price DECIMAL(10, 2) NOT NULL DEFAULT 0,
  price_unit VARCHAR(20) NOT NULL DEFAULT 'month',
  rating DECIMAL(3, 2) DEFAULT 5.0,
  user_count INTEGER DEFAULT 0,
  is_official BOOLEAN DEFAULT false,
  is_published BOOLEAN DEFAULT false,
  contact_info TEXT,
  demo_url TEXT,
  github_url TEXT,
  documentation_url TEXT,
  tags TEXT[],
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT check_rating CHECK (rating >= 0 AND rating <= 5)
);

-- Create market_product_categories table (商品分类表)
CREATE TABLE IF NOT EXISTS market_product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  description TEXT,
  icon VARCHAR(50),
  is_active BOOLEAN DEFAULT true,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create market_product_views table (商品浏览记录表)
CREATE TABLE IF NOT EXISTS market_product_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES market_products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create market_product_inquiries table (商品咨询记录表)
CREATE TABLE IF NOT EXISTS market_product_inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES market_products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  contact_method VARCHAR(50) NOT NULL,
  message TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_market_products_user_id ON market_products(user_id);
CREATE INDEX IF NOT EXISTS idx_market_products_category ON market_products(category);
CREATE INDEX IF NOT EXISTS idx_market_products_is_published ON market_products(is_published);
CREATE INDEX IF NOT EXISTS idx_market_products_is_official ON market_products(is_official);
CREATE INDEX IF NOT EXISTS idx_market_products_rating ON market_products(rating DESC);
CREATE INDEX IF NOT EXISTS idx_market_products_user_count ON market_products(user_count DESC);
CREATE INDEX IF NOT EXISTS idx_market_product_views_product_id ON market_product_views(product_id);
CREATE INDEX IF NOT EXISTS idx_market_product_views_viewed_at ON market_product_views(viewed_at DESC);
CREATE INDEX IF NOT EXISTS idx_market_product_inquiries_product_id ON market_product_inquiries(product_id);
CREATE INDEX IF NOT EXISTS idx_market_product_inquiries_user_id ON market_product_inquiries(user_id);

-- Enable Row Level Security
ALTER TABLE market_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_product_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_product_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_product_inquiries ENABLE ROW LEVEL SECURITY;

-- RLS Policies for market_products
-- Public can view published products
CREATE POLICY "Public can view published market products"
ON market_products FOR SELECT
USING (is_published = true);

-- Users can view their own products
CREATE POLICY "Users can view their own market products"
ON market_products FOR SELECT
USING (auth.uid() = user_id);

-- Users can insert their own products
CREATE POLICY "Users can insert their own market products"
ON market_products FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can update their own products
CREATE POLICY "Users can update their own market products"
ON market_products FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Users can delete their own products
CREATE POLICY "Users can delete their own market products"
ON market_products FOR DELETE
USING (auth.uid() = user_id);

-- RLS Policies for market_product_categories
-- Public can view active categories
CREATE POLICY "Public can view active market categories"
ON market_product_categories FOR SELECT
USING (is_active = true);

-- Service role can manage categories
CREATE POLICY "Service role can manage market categories"
ON market_product_categories FOR ALL
USING (auth.role() = 'service_role');

-- RLS Policies for market_product_views
-- Public can insert view records
CREATE POLICY "Public can insert market product views"
ON market_product_views FOR INSERT
WITH CHECK (true);

-- Users can view their own view records
CREATE POLICY "Users can view their own market product views"
ON market_product_views FOR SELECT
USING (auth.uid() = user_id);

-- RLS Policies for market_product_inquiries
-- Authenticated users can insert inquiries
CREATE POLICY "Authenticated users can insert market product inquiries"
ON market_product_inquiries FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can view their own inquiries
CREATE POLICY "Users can view their own market product inquiries"
ON market_product_inquiries FOR SELECT
USING (auth.uid() = user_id);

-- Product owners can view inquiries for their products
CREATE POLICY "Product owners can view inquiries for their products"
ON market_product_inquiries FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM market_products
    WHERE market_products.id = market_product_inquiries.product_id
    AND market_products.user_id = auth.uid()
  )
);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_market_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update updated_at for market_products
CREATE TRIGGER update_market_products_updated_at
BEFORE UPDATE ON market_products
FOR EACH ROW
EXECUTE FUNCTION update_market_updated_at();

-- Insert initial sample categories
INSERT INTO market_product_categories (name, display_name, description, icon, is_active, order_index) VALUES
  ('all', '全部分类', '显示所有分类的商品', 'shoppingBag', true, 0),
  ('assistant', '客服助手', '智能客服和助手工具', 'shieldCheck', true, 1),
  ('design', '设计工具', '设计和创意工具', 'zap', true, 2),
  ('marketing', '营销助手', '营销和推广工具', 'shoppingBag', true, 3)
ON CONFLICT (name) DO NOTHING;

-- Insert sample products (from the existing mock data)
INSERT INTO market_products (
  user_id, title, description, category, icon_type, icon_color,
  price, price_unit, rating, user_count, is_official, is_published,
  contact_info, order_index
) VALUES
  (
    NULL,
    '智能客服助手',
    'AI驱动的24/7在线客服，即时响应，显著提升客户满意度。',
    'assistant',
    'shield',
    'blue',
    99.00,
    'month',
    5.0,
    1234,
    true,
    true,
    NULL,
    1
  ),
  (
    NULL,
    'AI 设计生成器',
    '一键生成海报、Logo、UI界面，设计效率提升 5 倍。',
    'design',
    'zap',
    'purple',
    299.00,
    'month',
    5.0,
    3567,
    true,
    true,
    NULL,
    2
  ),
  (
    NULL,
    '营销文案专家',
    '自动撰写广告语、社交媒体内容，精准抓住用户痛点。',
    'marketing',
    'shoppingBag',
    'green',
    199.00,
    'month',
    5.0,
    2109,
    false,
    true,
    NULL,
    3
  ),
  (
    NULL,
    '全能数据分析师',
    '智能分析业务数据，提供可视化报表与决策支持。',
    'assistant',
    'star',
    'orange',
    499.00,
    'month',
    5.0,
    890,
    true,
    true,
    NULL,
    4
  )
ON CONFLICT DO NOTHING;
