-- ============================================================
-- Square Topics & Comments: tables, RLS
-- 碳硅广场话题和评论功能
-- ============================================================

-- 1. Create topics table (话题表)
CREATE TABLE IF NOT EXISTS public.topics (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title         text NOT NULL,
  content       text NOT NULL,
  image_url     text,
  category      text NOT NULL,              -- 话题分类，如 '#脑洞大开', '#避坑指南'
  tag           text,                        -- 用户标签，如 '技术先锋', '行业专家'
  likes_count   integer NOT NULL DEFAULT 0,
  comments_count integer NOT NULL DEFAULT 0,
  views_count   integer NOT NULL DEFAULT 0,
  published     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_topics_user_id ON public.topics(user_id);
CREATE INDEX IF NOT EXISTS idx_topics_category ON public.topics(category);
CREATE INDEX IF NOT EXISTS idx_topics_created_at ON public.topics(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_topics_published ON public.topics(published, created_at DESC);

COMMENT ON TABLE public.topics IS '碳硅广场话题表';

-- 2. Create topic_likes table (话题点赞表)
CREATE TABLE IF NOT EXISTS public.topic_likes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id      bigint NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE(topic_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_topic_likes_topic_id ON public.topic_likes(topic_id);
CREATE INDEX IF NOT EXISTS idx_topic_likes_user_id ON public.topic_likes(user_id);

COMMENT ON TABLE public.topic_likes IS '话题点赞表';

-- 3. Create comments table (评论表)
CREATE TABLE IF NOT EXISTS public.comments (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id      bigint NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
  parent_id     bigint,                        -- 支持嵌套回复，NULL 表示一级评论
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  content       text NOT NULL,
  likes_count   integer NOT NULL DEFAULT 0,
  replies_count integer NOT NULL DEFAULT 0,   -- 回复数量
  published     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comments_topic_id ON public.comments(topic_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON public.comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON public.comments(user_id);

COMMENT ON TABLE public.comments IS '话题评论表';

-- 4. Create comment_likes table (评论点赞表)
CREATE TABLE IF NOT EXISTS public.comment_likes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id    bigint NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE(comment_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_comment_likes_comment_id ON public.comment_likes(comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_likes_user_id ON public.comment_likes(user_id);

COMMENT ON TABLE public.comment_likes IS '评论点赞表';

-- 5. Trigger: 自动更新 topics.updated_at
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tr_topics_updated_at ON public.topics;
CREATE TRIGGER tr_topics_updated_at
  BEFORE UPDATE ON public.topics
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_updated_at_column();

DROP TRIGGER IF EXISTS tr_comments_updated_at ON public.comments;
CREATE TRIGGER tr_comments_updated_at
  BEFORE UPDATE ON public.comments
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_updated_at_column();

-- 6. Trigger: 点赞时自动更新 likes_count
-- 话题点赞
CREATE OR REPLACE FUNCTION public.update_topic_likes_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.topics SET likes_count = likes_count + 1 WHERE id = NEW.topic_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.topics SET likes_count = likes_count - 1 WHERE id = OLD.topic_id;
    RETURN OLD;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS tr_topic_likes_count ON public.topic_likes;
CREATE TRIGGER tr_topic_likes_count
  AFTER INSERT OR DELETE ON public.topic_likes
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_topic_likes_count();

-- 评论点赞
CREATE OR REPLACE FUNCTION public.update_comment_likes_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.comments SET likes_count = likes_count + 1 WHERE id = NEW.comment_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.comments SET likes_count = likes_count - 1 WHERE id = OLD.comment_id;
    RETURN OLD;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS tr_comment_likes_count ON public.comment_likes;
CREATE TRIGGER tr_comment_likes_count
  AFTER INSERT OR DELETE ON public.comment_likes
  FOR EACH ROW
  EXECUTE PROCEDURE public.update_comment_likes_count();

-- 7. Trigger: 评论时自动更新 comments_count 和 replies_count
CREATE OR REPLACE FUNCTION public_update_topic_comments_count()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- 更新话题的评论数
    UPDATE public.topics SET comments_count = comments_count + 1 WHERE id = NEW.topic_id;
    -- 如果是回复，更新父评论的回复数
    IF NEW.parent_id IS NOT NULL THEN
      UPDATE public.comments SET replies_count = replies_count + 1 WHERE id = NEW.parent_id;
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    -- 更新话题的评论数
    UPDATE public.topics SET comments_count = comments_count - 1 WHERE id = OLD.topic_id;
    -- 如果是回复，更新父评论的回复数
    IF OLD.parent_id IS NOT NULL THEN
      UPDATE public.comments SET replies_count = replies_count - 1 WHERE id = OLD.parent_id;
    END IF;
    RETURN OLD;
  END IF;
END;
$$;

DROP TRIGGER IF EXISTS tr_topic_comments_count ON public.comments;
CREATE TRIGGER tr_topic_comments_count
  AFTER INSERT OR DELETE ON public.comments
  FOR EACH ROW
  EXECUTE PROCEDURE public_update_topic_comments_count();

-- 8. RLS (Row Level Security)
-- 启用 RLS
ALTER TABLE public.topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.topic_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comment_likes ENABLE ROW LEVEL SECURITY;

-- topics 表策略
DROP POLICY IF EXISTS "Anyone can view published topics" ON public.topics;
CREATE POLICY "Anyone can view published topics"
  ON public.topics FOR SELECT
  USING (published = true);

DROP POLICY IF EXISTS "Users can insert own topics" ON public.topics;
CREATE POLICY "Users can insert own topics"
  ON public.topics FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own topics" ON public.topics;
CREATE POLICY "Users can update own topics"
  ON public.topics FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own topics" ON public.topics;
CREATE POLICY "Users can delete own topics"
  ON public.topics FOR DELETE
  USING (auth.uid() = user_id);

-- topic_likes 表策略
DROP POLICY IF EXISTS "Anyone can view topic likes" ON public.topic_likes;
CREATE POLICY "Anyone can view topic likes"
  ON public.topic_likes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert own topic likes" ON public.topic_likes;
CREATE POLICY "Users can insert own topic likes"
  ON public.topic_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own topic likes" ON public.topic_likes;
CREATE POLICY "Users can delete own topic likes"
  ON public.topic_likes FOR DELETE
  USING (auth.uid() = user_id);

-- comments 表策略
DROP POLICY IF EXISTS "Anyone can view published comments" ON public.comments;
CREATE POLICY "Anyone can view published comments"
  ON public.comments FOR SELECT
  USING (published = true);

DROP POLICY IF EXISTS "Users can insert own comments" ON public.comments;
CREATE POLICY "Users can insert own comments"
  ON public.comments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own comments" ON public.comments;
CREATE POLICY "Users can update own comments"
  ON public.comments FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own comments" ON public.comments;
CREATE POLICY "Users can delete own comments"
  ON public.comments FOR DELETE
  USING (auth.uid() = user_id);

-- comment_likes 表策略
DROP POLICY IF EXISTS "Anyone can view comment likes" ON public.comment_likes;
CREATE POLICY "Anyone can view comment likes"
  ON public.comment_likes FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert own comment likes" ON public.comment_likes;
CREATE POLICY "Users can insert own comment likes"
  ON public.comment_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own comment likes" ON public.comment_likes;
CREATE POLICY "Users can delete own comment likes"
  ON public.comment_likes FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================
-- 完成提示
-- ============================================================
-- 此脚本已创建以下表：
-- 1. topics - 话题表
-- 2. topic_likes - 话题点赞表
-- 3. comments - 评论表（支持嵌套回复）
-- 4. comment_likes - 评论点赞表
--
-- 功能包括：
-- - 自动更新点赞数和评论数的触发器
-- - 完整的 RLS 策略
-- - 用户标签和分类支持
