-- ============================================================
-- User Follows & Topic Notification
-- 用户关注功能和话题发布通知
-- ============================================================

-- 1. Create user_follows table (用户关注表)
CREATE TABLE IF NOT EXISTS public.user_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  following_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(follower_id, following_id)
);

CREATE INDEX IF NOT EXISTS idx_user_follows_follower ON public.user_follows(follower_id);
CREATE INDEX IF NOT EXISTS idx_user_follows_following ON public.user_follows(following_id);

COMMENT ON TABLE public.user_follows IS '用户关注关系表';

-- 2. Enable RLS
ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for user_follows
-- Users can view all follow relationships
CREATE POLICY "Anyone can view follows"
  ON public.user_follows FOR SELECT
  USING (true);

-- Users can follow/unfollow (insert/delete own records)
CREATE POLICY "Users can follow others"
  ON public.user_follows FOR INSERT
  WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow others"
  ON public.user_follows FOR DELETE
  USING (auth.uid() = follower_id);

-- 4. Trigger function: when a followed user publishes a topic, notify followers
CREATE OR REPLACE FUNCTION public.notify_followers_on_topic_publish()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  follower_rec RECORD;
  author_name TEXT;
BEGIN
  -- Get author display name from profiles
  SELECT COALESCE(full_name, '一位用户')
  INTO author_name
  FROM public.profiles
  WHERE id = NEW.user_id
  LIMIT 1;

  IF author_name IS NULL THEN
    author_name := '一位用户';
  END IF;

  -- Notify all followers
  FOR follower_rec IN
    SELECT follower_id FROM public.user_follows
    WHERE following_id = NEW.user_id
  LOOP
    INSERT INTO public.notifications (user_id, type, title, content, related_link, is_read)
    VALUES (
      follower_rec.follower_id,
      'new_topic',
      '关注用户发布新话题',
      format('%s 刚刚发布了一个新话题《%s》', author_name, NEW.title),
      '/?topic=' || NEW.id,
      false
    );
  END LOOP;

  RETURN NEW;
END;
$$;

-- 5. Trigger: AFTER INSERT on topics (only for published topics)
DROP TRIGGER IF EXISTS tr_notify_followers_on_topic_publish ON public.topics;
CREATE TRIGGER tr_notify_followers_on_topic_publish
  AFTER INSERT ON public.topics
  FOR EACH ROW
  WHEN (NEW.published = true)
  EXECUTE FUNCTION public.notify_followers_on_topic_publish();

-- 6. Update profiles table: add followers_count and following_count
-- (Optional: for displaying counts)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS followers_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS following_count INT DEFAULT 0;

-- 7. Trigger to update followers/following counts
CREATE OR REPLACE FUNCTION public.update_follow_counts()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- Increment counts
    UPDATE public.profiles
      SET followers_count = followers_count + 1
      WHERE id = NEW.following_id;
    UPDATE public.profiles
      SET following_count = following_count + 1
      WHERE id = NEW.follower_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    -- Decrement counts
    UPDATE public.profiles
      SET followers_count = GREATEST(followers_count - 1, 0)
      WHERE id = OLD.following_id;
    UPDATE public.profiles
      SET following_count = GREATEST(following_count - 1, 0)
      WHERE id = OLD.follower_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS tr_update_follow_counts ON public.user_follows;
CREATE TRIGGER tr_update_follow_counts
  AFTER INSERT OR DELETE ON public.user_follows
  FOR EACH ROW
  EXECUTE FUNCTION public.update_follow_counts();

-- 8. Grant permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON TABLE public.user_follows TO authenticated;
GRANT SELECT ON TABLE public.user_follows TO anon;
