-- ============================================================
-- In-App Notifications: table, trigger, RLS
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor).
-- ============================================================

-- 1. Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type          text NOT NULL,
  title         text NOT NULL,
  content       text NOT NULL,
  related_link  text,
  is_read       boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON public.notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications(created_at DESC);

COMMENT ON TABLE public.notifications IS 'In-app notifications for task creators (e.g. when a worker claims a task).';

-- 2. Trigger function: on task_claims INSERT, notify the task creator
-- Uses tasks_reward for creator and title. Worker name from auth.users with safe fallback.
CREATE OR REPLACE FUNCTION public.notify_creator_on_task_claim()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_creator_id uuid;
  v_task_title text;
  v_worker_display text := '一位开发者';
BEGIN
  -- Get creator and title from tasks_reward (id may be int8 or uuid; compare as text)
  SELECT t.user_id, COALESCE(t.title, '未命名任务')
  INTO v_creator_id, v_task_title
  FROM public.tasks_reward t
  WHERE t.id::text = (NEW.task_id)::text
  LIMIT 1;

  IF v_creator_id IS NULL THEN
    RETURN NEW;
  END IF;

  -- Worker display: try auth.users (may fail on permission in some Supabase setups)
  BEGIN
    SELECT COALESCE((SELECT u.email FROM auth.users u WHERE u.id = NEW.claimant_id LIMIT 1), '一位开发者')
    INTO v_worker_display;
  EXCEPTION WHEN OTHERS THEN
    v_worker_display := '一位开发者';
  END;

  INSERT INTO public.notifications (user_id, type, title, content, related_link, is_read)
  VALUES (
    v_creator_id,
    'task_application',
    '有人接单了',
    format('开发者 %s 刚刚领取了您的悬赏《%s》，请尽快联系。', v_worker_display, v_task_title),
    '/tasks#' || (NEW.task_id)::text,
    false
  );

  RETURN NEW;
END;
$$;

-- Trigger: AFTER INSERT on task_claims
DROP TRIGGER IF EXISTS tr_notify_creator_on_task_claim ON public.task_claims;
CREATE TRIGGER tr_notify_creator_on_task_claim
  AFTER INSERT ON public.task_claims
  FOR EACH ROW
  EXECUTE PROCEDURE public.notify_creator_on_task_claim();

-- If you use task_applications instead of task_claims, uncomment and adapt:
-- CREATE OR REPLACE FUNCTION public.notify_creator_on_task_application()
-- RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
-- DECLARE v_creator_id uuid; v_task_title text; v_worker_display text;
-- BEGIN
--   SELECT user_id, COALESCE(title, '未命名任务') INTO v_creator_id, v_task_title
--   FROM public.tasks_reward WHERE id::text = NEW.task_id::text LIMIT 1;
--   IF v_creator_id IS NULL THEN RETURN NEW; END IF;
--   SELECT COALESCE((SELECT email FROM auth.users WHERE id = NEW.worker_id LIMIT 1), '一位开发者') INTO v_worker_display;
--   INSERT INTO public.notifications (user_id, type, title, content, related_link, is_read)
--   VALUES (v_creator_id, 'task_application', '有人接单了',
--     format('开发者 %s 刚刚领取了您的悬赏《%s》，请尽快联系。', v_worker_display, v_task_title),
--     '/tasks#' || NEW.task_id, false);
--   RETURN NEW;
-- END; $$;
-- DROP TRIGGER IF EXISTS tr_notify_creator_on_task_application ON public.task_applications;
-- CREATE TRIGGER tr_notify_creator_on_task_application AFTER INSERT ON public.task_applications
--   FOR EACH ROW EXECUTE PROCEDURE public.notify_creator_on_task_application();

-- 3. RLS: users can only SELECT and UPDATE their own notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
CREATE POLICY "Users can read own notifications"
  ON public.notifications FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notifications" ON public.notifications;
CREATE POLICY "Users can update own notifications"
  ON public.notifications FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- No INSERT/DELETE by users (insert is done by trigger; delete optional later)
-- If you want users to delete their own notifications, add:
-- CREATE POLICY "Users can delete own notifications" ON public.notifications
--   FOR DELETE USING (auth.uid() = user_id);
